### ISSUE TITLE
Add more actions in addition to `left` and `right` to enable other ways of defining interactions or outcomes of cards

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#114]
This would allow for example timed events, that should trigger a third, hidden option `timeout` if the player didn't choose `left` or `right` within a set time.

But this could also be useful for other interactions like `up` or `down` to let players swipe in different directions.

Just some ideas 💡

**Comment by Muthaias** [comment]
I would also suggest renaming actions into something descriptive like `approve` or `decline`, `endorse` and `oppose`

**Comment by Greenheart** [comment]
Yeah that's a very good point! It would make it easier to describe the game content, which would make it easier to develop scenarios.

One issue though is the current smooth API with `addAction()`, `setAction()` etc. Renaming `Action` to `Approve` could make the content API harder to understand logically. `setApprove()` is very unclear for example.


Or wait... Do you mean changing for example `left` to `decline`? In that case, we could still use `action` as a general term to describe any kind of `action`, not just `left` and `right`.

This would be a good balance between communicating intent in game content structure (`approve` is much better than `right`), while also allowing us to keep the current content API and the broad term`action`.

**Comment by Greenheart** [comment]
I think we should stick with the actions `left` and `right`, to focus on the MVP instead. Closing to allow us to focus better on actual issues. Ans this could be revisited in the future if we want to - at which point we may want to define the available `actions` through data + mods/extensions to implement them in the main game module
