### ISSUE TITLE
Re-implement dev tools for new GameScenario

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#116]
We want to re-implement the dev tools (i.e state logging) in a cleaner less intrusive way. This can be done by extending the class BasicGameScenario and overriding selected function adding logging or a stream to a developer toolbar.

**Comment by Greenheart** [comment]
Idea: activate dev tools automatically for localhost:

```
// Enable DEV_TOOLS for local development by default to improve DX
// window.DEV_TOOLS_ACTIVE = window.location.hostname.includes('localhost')
```

**Comment by Greenheart** [comment]
Improved dev tools could be added using the new `WorldStateExtensions` https://github.com/Greenheart/swipeforfuture.com/blob/master/src/game/WorldStateExtensions.ts
