### ISSUE TITLE
Refactor code with the goal of removing legacy code and drastically reducing binary size

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#160]
I think that the initial refactor of the main logic has been proven to work quite well and I think it is time to strip out some legacy code and types in order to get a leaner code base.

I would like to:
* Reduce the code size of the deployed site
* Update the loaded data format
* Adjust parameters to only be limited to [0-100] if they are part of the visible game state
* [Optional] Maybe strip out React and some of the UI-libraries used

The goal is twofold:
* Reduce the amount of code to maintain
* Reduce the initial download footprint

I would like your input before starting this @Greenheart

**Comment by Greenheart** [comment]
This would be a really fun project this coming week! I have similar ideas about simplifying the game 😃

**Comment by Greenheart** [comment]
For example, I've been working with https://svelte.dev for the last 8 months and really enjoyed how much it simplifies the equivalent React code.

One idea is to refactor the game to use Svelte (possibly with https://kit.svelte.dev and `adapter-static` to get a solid foundation). Svelte includes animation and transitions, which makes it easy to create the card stack animations we previously used `react-spring` for:

This is almost the card swipe animation:
https://svelte.dev/examples#actions

**Comment by Greenheart** [comment]
Everything in this issue except `Adjust parameters to only be limited to [0-100] if they are part of the visible game state` is solved! :)
