### ISSUE TITLE
Remove the scrollbar triggered by dragging a card downwards

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#164]
To replicate:
* Drag card towards the bottom of the screen such that it passes the bottom of the window
* A scrollbar appears (This scrollbar should be disabled)

**Comment by Greenheart** [comment]
Fixed by https://github.com/Greenheart/swipeforfuture.com/commit/f4c769216438f9d77170b9b4693a197ed9f9170f
