### ISSUE TITLE
inspiration from flashcards: duration of swiping a single card(making a decision)

### ISSUE THREAD

**Issue by thecrossed** [Greenheart/swipeforfuture.com#17]
As the game moves on, the content(decision/situation) becomes complicated, the longer will a player make a decision. (But how to set difficulty levels of the content?)

**Comment by Greenheart** [comment]
For example, the first decisions (cards) could be easy to teach players how the game works. Then they get harder further on and players need to take more time to make decisions and think about consequences.

**Comment by Greenheart** [comment]
Thanks for your input Tianmin! We're going to think about this going forward when we create content. The plan is to add an easy scenario where players get to learn the core concepts of the game by simply playing.
