### ISSUE TITLE
Idea: Show aggregated anonymized data on decisions to give a better understanding of the climate movement's goals and challenges

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#20]
Presenting this data could hopefully help people in the movement (and also politicians) understand the challenges and trade offs.

By using anonymized data, personal integrity would not be affected.

**Comment by thecrossed** [comment]
would you please offer an example?

**Comment by Greenheart** [comment]
@thecrossed one example could be to gather data of how players make decisions. For example, if 90% of players go for investing in renewables, that could say something about what players think of the solutions. Then players could get this visualized on some statistics page. Or it could potentially be interesting to politicians or scientists.

But - since this would require more work, this is probably not something for the first version of the game. Especially if we can't see the value in it.

**Comment by Greenheart** [comment]
Will not be implemented as this is no longer interesting.
