### ISSUE TITLE
Idea: Only allow a limited amount of swipes per day (maybe 5-10?)

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#21]
This could be a way to get players to come back.

But it could also hurt the fun in the game - since they can't have crazy, intense game sessions if they have the serious decisions.

If you have a sense of progress, this idea could be the hook that gets people coming back

**Comment by Greenheart** [comment]
If players have a limited set of swipes, they can also have a profile that shows all their decisions, and how their presidency is working out over time. (in the last 10 days and overall, all time)

Another interesting idea is to show graphs, to show your progress over time. One line for each variable, and shown over time, with points for each decision marked so you can see how decisions affected your presidency score.

The presidency score could be an average of your variables.

Decisions could be reviewed by scientists. Values don't have to be perfect, but they have to be explainable.

**Comment by thecrossed** [comment]
> This could be a way to get players to come back.
> 
> But it could also hurt the fun in the game - since they can't have crazy, intense game sessions if they have the serious decisions.
> 
> If you have a sense of progress, this idea could be the hook that gets people coming back

The idea is great! And I think the interval can range from minutes to days. Clash of Clans (a mobile game I often play) also adopts this strategy to make its players come back.

**Comment by Greenheart** [comment]
@thecrossed thanks for the feedback! This idea could be anything from 1 hour to 24 hours. What would be a good limit?

With 1 hour, it would allow several sessions per day, which would allow a faster pace. But 20 hours would build the daily habit.

Since it's pretty easy to swipe away the daily swipes, it would have to be possible to slow down the gameplay and show players how they can make more informed decisions by tapping cards and looking at the details at the back. This way, the 5-10 swipes would make sense. But if it's too easy to mindlessly swipe away cards, it could kill the fun in it.

**Comment by Muthaias** [comment]
While I would like this idea in a multiplayer setting (in order to control the action rate of players). I personally would prefer to be able to play the game at my own pace making decisions whenever I feel like it instead of being limited by an arbitrary rule.

If we simplify the contributions process for adding new cards I think the discovery of new cards could be the another reason for players to come back.

**Comment by Greenheart** [comment]
Yeah the limited number of decisions would be better for multiplayer.

Also, I really like the idea of making it easy to add new cards. I have started a Google Form to allow people to easily submit their ideas. But we could probably think of a much better way in the future.

"Themes" could be different main story lines, unlocking different cards specific only to that theme/storyline:
- Climate breakdown and total collapse of the human civilization. Scattered survivors.
- "The last emperor of Rome": luxury and excess for a short period of time, and then deal with the consequences.
- The path towards the sustainable Utopia (intentional exaggeration to make it clearly distinct from the other two paths.)

**Comment by hugobille** [comment]
I've been thinking about designs like this lately, and find that they have great potential in raising player focus and retention, but I'm most excited about how it encourages thinking about the game when not playing it. Consider if you get to see your upcoming 10 swipes (or a subset of them), but you don't get to make the decisions until after the cooldown. Gives you plenty of time to think about what you want to do. 

Still, this is controversial design as Muthaias mentioned, so might need a way to circumvent it.

**Comment by Muthaias** [comment]
This is no longer in line with the current design of target the gameplay. It is possible this may be reconsidered in the future if multiplayer is added. For now this is considered a closed topic.
