### ISSUE TITLE
Decide which OSS licence to use

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#28]
https://firstdonoharm.dev/ could be a good option.

**Comment by Muthaias** [comment]
I would approve of this one. Or any strict GPL variant. But I guess MIT is also fine :)

Personally I think this issue should be prioritized in order to be clear towards contributors.

**Comment by Greenheart** [comment]
I agree, this is important to allow others to contribute. Let's go with MIT. I'll add it later tonight :)
