### ISSUE TITLE
Idea: Theme based card selection for a single game

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#30]
In order to make the game more replay friendly we could add "themes" to the cards in order to limit the card selection when starting a game. This way a player would not be exposed to the same cards as many times since one could choose different scenarios or themes.

Cards should of course be possible to share between different themes.

(This might require a quite streamlined card production pipeline and guidelines since it could get quite content heavy.)

**Comment by Greenheart** [comment]
I like the idea of having multiple distinct themes or story lines. It would set the general direction of the game content.

However, this will have to wait for now as this needs more content. Let's keep this to V2 though! 🙂

**Comment by Greenheart** [comment]
This idea would be possible to implement with multiple `GameWorld`s that set their own "theme".

Sharing content between `GameWorld`s could also be added if we wanted to.

**Comment by Muthaias** [comment]
This can now be achieved using different entrypoints for data loading.
