### ISSUE TITLE
Visual indicators of consequences of decisions

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#53]
When a card is active, show visual indicators of how the decision will impact the game world. This will help players make their decisions.

## This could be done in several ways:

1. a dot above the icon to indicate how the value will change. Large dot meaning increasing, small dot meaning decreasing.
2. Highlight the difference inside of the bar below each icon for a given choice. Green bar meaning increasing and red bar meaning decreasing.

**Comment by Muthaias** [comment]
A visual example can be found here: https://youtu.be/0FamZL3nwPg?feature=shared&t=143
