### ISSUE TITLE
Add editing to devtools panel

### ISSUE THREAD

**Issue by Muthaias** [Greenheart/swipeforfuture.com#90]
Enable:
* Selecting currently viewed card from a list
* Editing card properties
* Adding new cards
* Remove existing cards
* Dump data and/or upload data to backend

**Comment by Greenheart** [comment]
This would still be a nice feature, but it would probably require much work to get right.

So let's stick to the MVP issues for now and then we can reopen this in the future once we have stable content scripting utilities.
