### ISSUE TITLE
Potential bug: the same event card appears twice in `availableCards`

### ISSUE THREAD

**Issue by Greenheart** [Greenheart/swipeforfuture.com#91]
See screenshot and console output to see that 

![image](https://user-images.githubusercontent.com/6125097/82697989-449fa100-9c6a-11ea-90ff-9b4d5838adf7.png)

Here are the world stats at this stage too:
![image](https://user-images.githubusercontent.com/6125097/82698708-939a0600-9c6b-11ea-8119-dacd5d9f8c25.png)

**Comment by Muthaias** [comment]
Those cards are not equal. One has an additional string value in the `distance` property. I would say that it is probably a `data bug` if anything. If you check out the `cards.json` file you will notice that there are two copies of this card with a slight difference.
